displayName=Combat Achievement Helper
author=opaf
support=https://github.com/opaf-osrs/combat-achievement-helper/issues
description=Recommends your next Combat Achievements and routes you to your next tier
tags=combat,achievements,ca,pvm,progression,tasks,tiers,guide
plugins=com.pluginideahub.combatachievements.CombatAchievementsPlugin
build=standard
